# Generated by Django 6.0 on 2026-01-03 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('activities', 'Activities'), ('coding-activities', 'Coding Activities'), ('presentations', 'Presentations'), ('projects', 'Projects')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=48, unique=True)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-start_year', '-end_year'],
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StandardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=140, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artifact_images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.artifact')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='artifact_videos/%Y/%m/')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='portfolio.artifact')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='portfolio.schoolyear'),
        ),
        migrations.CreateModel(
            name='ArtifactStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_standards', to='portfolio.artifact')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_standards', to='portfolio.standard')),
            ],
            options={
                'ordering': ['standard__category__name', 'standard__code'],
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='standards',
            field=models.ManyToManyField(blank=True, related_name='artifacts', through='portfolio.ArtifactStandard', to='portfolio.standard'),
        ),
        migrations.AddField(
            model_name='standard',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standards', to='portfolio.standardcategory'),
        ),
        migrations.AddConstraint(
            model_name='artifactstandard',
            constraint=models.UniqueConstraint(fields=('artifact', 'standard'), name='uniq_standard_per_artifact'),
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.UniqueConstraint(fields=('school_year', 'category', 'slug'), name='uniq_artifact_slug_per_year_category'),
        ),
        migrations.AddConstraint(
            model_name='standard',
            constraint=models.UniqueConstraint(fields=('category', 'code'), name='uniq_standard_code_per_category'),
        ),
    ]
