# Generated by Django 6.0.1 on 2026-01-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardcategory',
            name='slug',
        ),
    ]
